# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nguyenvuminh/cpp-project/traffic-simulation-group-3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nguyenvuminh/cpp-project/traffic-simulation-group-3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nguyenvuminh/cpp-project/traffic-simulation-group-3/CMakeFiles /home/nguyenvuminh/cpp-project/traffic-simulation-group-3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nguyenvuminh/cpp-project/traffic-simulation-group-3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TrafficSimulator

# Build rule for target.
TrafficSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrafficSimulator
.PHONY : TrafficSimulator

# fast build rule for target.
TrafficSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/build
.PHONY : TrafficSimulator/fast

src/building.o: src/building.cpp.o
.PHONY : src/building.o

# target to build an object file
src/building.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/building.cpp.o
.PHONY : src/building.cpp.o

src/building.i: src/building.cpp.i
.PHONY : src/building.i

# target to preprocess a source file
src/building.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/building.cpp.i
.PHONY : src/building.cpp.i

src/building.s: src/building.cpp.s
.PHONY : src/building.s

# target to generate assembly for a file
src/building.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/building.cpp.s
.PHONY : src/building.cpp.s

src/car.o: src/car.cpp.o
.PHONY : src/car.o

# target to build an object file
src/car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/car.cpp.o
.PHONY : src/car.cpp.o

src/car.i: src/car.cpp.i
.PHONY : src/car.i

# target to preprocess a source file
src/car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/car.cpp.i
.PHONY : src/car.cpp.i

src/car.s: src/car.cpp.s
.PHONY : src/car.s

# target to generate assembly for a file
src/car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/car.cpp.s
.PHONY : src/car.cpp.s

src/city.o: src/city.cpp.o
.PHONY : src/city.o

# target to build an object file
src/city.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/city.cpp.o
.PHONY : src/city.cpp.o

src/city.i: src/city.cpp.i
.PHONY : src/city.i

# target to preprocess a source file
src/city.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/city.cpp.i
.PHONY : src/city.cpp.i

src/city.s: src/city.cpp.s
.PHONY : src/city.s

# target to generate assembly for a file
src/city.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/city.cpp.s
.PHONY : src/city.cpp.s

src/intersection.o: src/intersection.cpp.o
.PHONY : src/intersection.o

# target to build an object file
src/intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/intersection.cpp.o
.PHONY : src/intersection.cpp.o

src/intersection.i: src/intersection.cpp.i
.PHONY : src/intersection.i

# target to preprocess a source file
src/intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/intersection.cpp.i
.PHONY : src/intersection.cpp.i

src/intersection.s: src/intersection.cpp.s
.PHONY : src/intersection.s

# target to generate assembly for a file
src/intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/intersection.cpp.s
.PHONY : src/intersection.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/person.o: src/person.cpp.o
.PHONY : src/person.o

# target to build an object file
src/person.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/person.cpp.o
.PHONY : src/person.cpp.o

src/person.i: src/person.cpp.i
.PHONY : src/person.i

# target to preprocess a source file
src/person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/person.cpp.i
.PHONY : src/person.cpp.i

src/person.s: src/person.cpp.s
.PHONY : src/person.s

# target to generate assembly for a file
src/person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/person.cpp.s
.PHONY : src/person.cpp.s

src/road.o: src/road.cpp.o
.PHONY : src/road.o

# target to build an object file
src/road.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/road.cpp.o
.PHONY : src/road.cpp.o

src/road.i: src/road.cpp.i
.PHONY : src/road.i

# target to preprocess a source file
src/road.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/road.cpp.i
.PHONY : src/road.cpp.i

src/road.s: src/road.cpp.s
.PHONY : src/road.s

# target to generate assembly for a file
src/road.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrafficSimulator.dir/build.make CMakeFiles/TrafficSimulator.dir/src/road.cpp.s
.PHONY : src/road.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TrafficSimulator"
	@echo "... src/building.o"
	@echo "... src/building.i"
	@echo "... src/building.s"
	@echo "... src/car.o"
	@echo "... src/car.i"
	@echo "... src/car.s"
	@echo "... src/city.o"
	@echo "... src/city.i"
	@echo "... src/city.s"
	@echo "... src/intersection.o"
	@echo "... src/intersection.i"
	@echo "... src/intersection.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/person.o"
	@echo "... src/person.i"
	@echo "... src/person.s"
	@echo "... src/road.o"
	@echo "... src/road.i"
	@echo "... src/road.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

